const itemCodes = [

    // Sword
    {name: "Wooden Dagger", code: 101, grade: 1},
    {name: "Gradius", code: 102, grade: 1},
    {name: "Long Sword", code: 103, grade: 1},
    {name: "Copper Sword", code: 104, grade: 1},
    {name: "Sword of Knight", code: 105, grade: 1},
    {name: "Advanced Long Sword", code: 111, grade: 2},
    {name: "Flamberge", code: 112, grade: 2},
    {name: "Broad Sword", code: 113, grade: 2},
    {name: "Masamune", code: 114, grade: 2},
    {name: "Predator's Great Sword", code: 115, grade: 2},
    {name: "Sword Breaker", code: 121, grade: 3},
    {name: "Rapier", code: 122, grade: 3},
    {name: "The Dead Princess' Falcata", code: 123, grade: 3},
    {name: "The Great Sword of New Moon", code: 124, grade: 3},
    {name: "Titanium Sword", code: 125, grade: 3},
    {name: "The Crescent", code: 131, grade: 4},
    {name: "The God's Strike", code: 132, grade: 4},
    {name: "The Great Sword Against Death", code: 133, grade: 4},
    {name: "Raphael's Sword", code: 134, grade: 4},
    {name: "Special Frying Pan", code: 135, grade: 4},
    {name: "Tulip Garden Sword", code: 136, grade: 4},
    {name: "Steel Goblin's Sword", code: 137, grade: 4},
    {name: "Black Dragon's Sword", code: 138, grade: 4},
    {name: "Excalibur", code: 141, grade: 5},
    {name: "Blood Sword", code: 142, grade: 5},
    {name: "Anria's Sword", code: 143, grade: 5},
    {name: "Berserker's Sword", code: 144, grade: 5},
    {name: "Dan's Sword", code: 151, grade: 6},

    // Axe
    {name: "Hand Axe", code: 201, grade: 1},
    {name: "Double-edged Axe", code: 202, grade: 1},
    {name: "Dagger Axe", code: 203, grade: 1},
    {name: "Broad Axe", code: 204, grade: 1},
    {name: "Battle Axe", code: 205, grade: 1},
    {name: "Tomahawk", code: 211, grade: 2},
    {name: "Bone Tomahawk", code: 212, grade: 2},
    {name: "Pierrot's Hand Axe", code: 213, grade: 2},
    {name: "The Slaughterer's Axe", code: 214, grade: 2},
    {name: "Dwarf", code: 215, grade: 2},
    {name: "Advanced Dwarf Axe", code: 221, grade: 3},
    {name: "Hurricane Halberd", code: 222, grade: 3},
    {name: "The Dead Princess' Axe", code: 223, grade: 3},
    {name: "Chilling Axe", code: 224, grade: 3},
    {name: "Titanium Axe", code: 225, grade: 3},
    {name: "Mithryl Hammer", code: 226, grade: 3},
    {name: "The Full Moon", code: 231, grade: 4},
    {name: "The Punishment of God", code: 232, grade: 4},
    {name: "The Battle Axe Against Death", code: 233, grade: 4},
    {name: "Cheese Hammer", code: 234, grade: 4},
    {name: "Giant Crab Axe", code: 235, grade: 4},
    {name: "Steel Goblin's Axe", code: 236, grade: 4},
    {name: "Black Dragon's Axe", code: 237, grade: 4},
    {name: "King's Axe", code: 241, grade: 5},
    {name: "Berserker's Axe", code: 242, grade: 5},

    // Bow
    {name: "Wooden Bow", code: 301, grade: 1},
    {name: "Recurve Bow", code: 302, grade: 1},
    {name: "Assassin's Bow", code: 303, grade: 1},
    {name: "Crossbow", code: 304, grade: 1},
    {name: "Advanced Wood Bow", code: 305, grade: 1},
    {name: "Korean Bow", code: 311, grade: 2},
    {name: "Battle Bow", code: 312, grade: 2},
    {name: "Silver Bone Bow", code: 313, grade: 2},
    {name: "Advanced Crossbow", code: 314, grade: 2},
    {name: "Opal Bow", code: 315, grade: 2},
    {name: "Red Bone Bow", code: 321, grade: 3},
    {name: "Poisonous Crossbow", code: 322, grade: 3},
    {name: "The Dead Princess' Bow", code: 323, grade: 3},
    {name: "Unicorn Bow", code: 324, grade: 3},
    {name: "Titanium Bow", code: 325, grade: 3},
    {name: "Mithryl Bow", code: 326, grade: 3},
    {name: "The Half Moon", code: 331, grade: 4},
    {name: "The Power of God", code: 332, grade: 4},
    {name: "The Crossbow Against Death", code: 333, grade: 4},
    {name: "Doric Bow", code: 334, grade: 4},
    {name: "Tulip Garden Bow", code: 335, grade: 4},
    {name: "Black Dragon's Bow", code: 336, grade: 4},
    {name: "King's Crossbow", code: 341, grade: 5},
    {name: "Anria's Bow", code: 342, grade: 5},

    // Staff
    {name: "Rod", code: 401, grade: 1},
    {name: "Staff", code: 402, grade: 1},
    {name: "Wand", code: 403, grade: 1},
    {name: "Rune Staff", code: 404, grade: 1},
    {name: "Battle Staff", code: 405, grade: 1},
    {name: "Shaman Wand", code: 411, grade: 2},
    {name: "Great Wand", code: 412, grade: 2},
    {name: "Solder Rod", code: 413, grade: 2},
    {name: "Blue Bell Rod", code: 414, grade: 2},
    {name: "Predator's Staff", code: 415, grade: 2},
    {name: "Mystic Rod", code: 421, grade: 3},
    {name: "Marionette", code: 422, grade: 3},
    {name: "The Forbidden Staff", code: 423, grade: 3},
    {name: "Soul Eater", code: 424, grade: 3},
    {name: "Mithryl Staff", code: 425, grade: 3},
    {name: "The New Moon", code: 431, grade: 4},
    {name: "God's Spell", code: 432, grade: 4},
    {name: "The Staff Against Death", code: 433, grade: 4},
    {name: "Raphael's Staff", code: 434, grade: 4},
    {name: "Doric Staff", code: 435, grade: 4},
    {name: "Giant Crab Staff", code: 436, grade: 4},
    {name: "Black Dragon's Staff", code: 437, grade: 4},
    {name: "King's Sceptre", code: 441, grade: 5},
    {name: "Black Wizard's Staff", code: 442, grade: 5},

    // Leather Armor
    {name: "Basic Robe", code: 501, grade: 1},
    {name: "Robe", code: 502, grade: 1},
    {name: "Black Robe", code: 503, grade: 1},
    {name: "Red Robe", code: 504, grade: 1},
    {name: "Leather Armor", code: 505, grade: 1},
    {name: "Green Robe", code: 511, grade: 2},
    {name: "Advanced Leather Armor", code: 512, grade: 2},
    {name: "Light Blue Robe", code: 513, grade: 2},
    {name: "Green Leather Armor", code: 514, grade: 2},
    {name: "Peacock Robe", code: 515, grade: 2},
    {name: "Chief Sorcerer's Robe", code: 521, grade: 3},
    {name: "Robe of the Noble", code: 522, grade: 3},
    {name: "Admiral's Robe", code: 523, grade: 3},
    {name: "Diabolic Armor", code: 524, grade: 3},
    {name: "The King Arthur's Class", code: 531, grade: 4},
    {name: "Mare Tranquilitatis", code: 532, grade: 4},
    {name: "The Armor Against Death", code: 533, grade: 4},
    {name: "Doric Robe", code: 534, grade: 4},
    {name: "Giant Crab Armor", code: 535, grade: 4},

    // Plate Armor
    {name: "Bronze Armor", code: 601, grade: 1},
    {name: "Iron Armor", code: 602, grade: 1},
    {name: "Half Plate Armor", code: 603, grade: 1},
    {name: "Plate Armor", code: 604, grade: 1},
    {name: "Chain Armor", code: 605, grade: 1},
    {name: "Full Plate Armor", code: 611, grade: 2},
    {name: "Warrior's Armor", code: 612, grade: 2},
    {name: "Paladin's Armor", code: 613, grade: 2},
    {name: "Dark Chain Armor", code: 614, grade: 2},
    {name: "Hero's Armor", code: 615, grade: 2},
    {name: "Vampire Plate", code: 621, grade: 3},
    {name: "Skeleton Plate Armor", code: 622, grade: 3},
    {name: "Red Heart Armor", code: 623, grade: 3},
    {name: "Magical Engineering Armor", code: 624, grade: 3},
    {name: "Titanium Armor", code: 625, grade: 3},
    {name: "Mithryl Armor", code: 626, grade: 3},
    {name: "Mare Serenitatis", code: 631, grade: 4},
    {name: "The Divine Protection", code: 632, grade: 4},
    {name: "The Sage's Plate Armor", code: 633, grade: 4},
    {name: "Raphael's Armor", code: 634, grade: 4},
    {name: "Steel Goblin's Armor", code: 635, grade: 4},
    {name: "King's Armor", code: 641, grade: 5},
    {name: "Anria's Armor", code: 642, grade: 5},
    {name: "Black Wizard's Armor", code: 643, grade: 5},
    {name: "Berserker's Armor", code: 644, grade: 5},

    // Ring
    {name: "Wood Ring", code: 701, grade: 1},
    {name: "Copper Ring", code: 702, grade: 1},
    {name: "Wave Ring", code: 703, grade: 1},
    {name: "Double Wave Ring", code: 704, grade: 1},
    {name: "Flower Ring", code: 705, grade: 1},
    {name: "Bone Ring", code: 711, grade: 2},
    {name: "Emerald Ring", code: 712, grade: 2},
    {name: "Gold Ring", code: 713, grade: 2},
    {name: "Pearl Ring", code: 714, grade: 2},
    {name: "Dark Ruby Ring", code: 715, grade: 2},
    {name: "Titanium Ring", code: 721, grade: 3},
    {name: "Admiral Ring", code: 722, grade: 3},
    {name: "Diamond Ring", code: 723, grade: 3},
    {name: "Pterosaur Ring", code: 724, grade: 3},
    {name: "Mithryl Ring", code: 725, grade: 3},
    {name: "The Blessings of Angels", code: 731, grade: 4},
    {name: "The Divine Promise", code: 732, grade: 4},
    {name: "The Clear Night Sky", code: 733, grade: 4},
    {name: "The Golden Promise", code: 741, grade: 5},
    {name: "Blood Ring", code: 742, grade: 5},
    {name: "King's Ring", code: 743, grade: 5},
    {name: "Anria's Ring", code: 744, grade: 5},

    // Amulet
    {name: "Wooden Necklace", code: 801, grade: 1},
    {name: "Copper Necklace", code: 802, grade: 1},
    {name: "Dew of Dawn", code: 803, grade: 1},
    {name: "Rosario", code: 804, grade: 1},
    {name: "Pure Gold Necklace", code: 805, grade: 1},
    {name: "Butterfly Brooch", code: 811, grade: 2},
    {name: "Brooch", code: 812, grade: 2},
    {name: "Deep Night Dew", code: 813, grade: 2},
    {name: "Clover Pendant", code: 814, grade: 2},
    {name: "Cursed Chain Necklace", code: 815, grade: 2},
    {name: "Special Medal", code: 821, grade: 3},
    {name: "Medal of the Predator", code: 822, grade: 3},
    {name: "Teach's Pocket Watch", code: 823, grade: 3},
    {name: "The Dead Princess' Necklace", code: 824, grade: 3},
    {name: "Call of MEET.ONE", code: 825, grade: 3},
    {name: "Juliet's Heart", code: 831, grade: 4},
    {name: "Mare Spumans", code: 832, grade: 4},
    {name: "The Promise Against Death", code: 833, grade: 4},
    {name: "Raphael's Star", code: 834, grade: 4},
    {name: "Doric Harp", code: 835, grade: 4},
    {name: "Cat Bell", code: 836, grade: 4},
    {name: "The Secret of Tulip Garden", code: 837, grade: 4},
    {name: "Steel Goblin's Stone", code: 838, grade: 4},
    {name: "Black Wizard's Eyes", code: 841, grade: 5},
    {name: "Berserker's Medal", code: 842, grade: 5},
]

module.exports = itemCodes;