const materialCodes = [
    { name: "Cheese Stone", code: 201, type: 2, grade: 3 },
    { name: "Elemental Mushroom", code: 202, type: 1, grade: 4 },
    { name: "Jade Skull", code: 203, type:3, grade: 5 },

    { name: "Crab Shell", code: 204, type:3, grade: 3 },
    { name: "Blowfish Poison", code: 205, type: 1, grade: 4 },
    { name: "Blue Scales", code: 206, type: 4, grade: 5 },

    { name: "Trumpet Flower", code: 207, type: 1, grade: 3 },
    { name: "Leaf of the Elves", code: 208, type: 1, grade: 4 },
    { name: "Red Tulip", code: 209, type: 1, grade: 5 },

    { name: "Red Horn", code: 210, type:3, grade: 3 },
    { name: "Blood Stone", code: 211, type: 1, grade: 4 },
    { name: "Steel Heart", code: 212, type: 2, grade: 5 },

    { name: "Dragon's Eye", code: 213, type: 1, grade: 3 },
    { name: "Onyx", code: 214, type: 5, grade: 4 },
    { name: "CPU", code: 215, type: 5, grade: 5 },

    { name: "The Golden Giants Blood", code: 11, type: 1, grade: 5 },
    { name: "Golden Bloodium", code: 31, type: 2, grade: 5 },
    { name: "Golden Skeleton King Skull", code: 51, type:3, grade: 5 },
    { name: "Ancient Dragon's Golden Leather", code: 71, type: 4, grade: 5 },
    { name: "Golden Lapis Lazuli", code: 91, type: 5, grade: 5 },

    { name: "The Giant's Blood", code: 10, type: 1, grade: 4 },
    { name: "Bloodium", code: 30, type: 2, grade: 4 },
    { name: "Skeleton King Skull", code: 50, type:3, grade: 4 },
    { name: "Ancient Dragon's Leather", code: 70, type: 4, grade: 4 },
    { name: "Lapis Lazuli", code: 90, type: 5, grade: 4 },

    { name: "Luminous Evening Primrose", code: 8, type: 1, grade: 3 },
    { name: "The Pirate King's Heart", code: 9, type: 1, grade: 3 },
    { name: "Mithryl", code: 28, type: 2, grade: 3 },
    { name: "Adamantium", code: 29, type: 2, grade: 3 },
    { name: "Pterosaur Claw", code: 48, type: 3, grade: 3 },
    { name: "Unicorn Horn", code: 49, type: 3, grade: 3 },
    { name: "Pterosaur Leather", code: 68, type: 4, grade: 3 },
    { name: "Mithryl Chiffon", code: 69, type: 4, grade: 3 },
    { name: "Peridot", code: 88, type: 5, grade: 3 },
    { name: "Moonstone", code: 89, type: 5, grade: 3 },

    { name: "Superior Smelting Stone", code: 5, type: 1, grade: 2 },
    { name: "Feather of a peacock", code: 6, type: 1, grade: 2 },
    { name: "Poison Frog", code: 7, type: 1, grade: 2 },
    { name: "Pyrites", code: 25, type: 2, grade: 2 },
    { name: "Magnesium ", code: 26, type: 2, grade: 2 },
    { name: "Titanium", code: 27, type: 2, grade: 2.5 },
    { name: "Bison Horn", code: 45, type: 3, grade: 2 },
    { name: "Tiger Bone", code: 46, type: 3, grade: 2 },
    { name: "Smilodon Tooth", code: 47, type: 3, grade: 2 },
    { name: "Chain Fabric", code: 65, type: 4, grade: 2 },
    { name: "Tiger leather", code: 66, type: 4, grade: 2 },
    { name: "Velvet", code: 67, type: 4, grade: 2 },
    { name: "Opal", code: 85, type: 5, grade: 2 },
    { name: "Diamond", code: 86, type: 5, grade: 2 },
    { name: "Cat's Eye", code: 87, type: 5, grade: 2 },

    { name: "Wood", code: 1, type: 1, grade: 1 },
    { name: "Smelting Stone", code: 2, type: 1, grade: 1 },
    { name: "Papyrus", code: 3, type: 1, grade: 1 },
    { name: "Poisonous mushroom", code: 4, type: 1, grade: 1 },
    { name: "Bronze", code: 21, type: 2, grade: 1 },
    { name: "Copper", code: 22, type: 2, grade: 1 },
    { name: "Iron", code: 23, type: 2, grade: 1 },
    { name: "Steel", code: 24, type: 2, grade: 1 },
    { name: "Bison Bone", code: 41, type: 3, grade: 1 },
    { name: "Ram Skull", code: 42, type: 3, grade: 1 },
    { name: "Wild Boar Tooth", code: 43, type: 3, grade: 1 },
    { name: "Bear Claw", code: 44, type: 3, grade: 1 },
    { name: "Cotton", code: 61, type: 4, grade: 1 },
    { name: "Tweed", code: 62, type: 4, grade: 1 },
    { name: "Cowhide", code: 63, type: 4, grade: 1 },
    { name: "Satin", code: 64, type: 4, grade: 1 },
    { name: "Sapphire", code: 81, type: 5, grade: 1 },
    { name: "Emerald", code: 82, type: 5, grade: 1 },
    { name: "Ruby", code: 83, type: 5, grade: 1 },
    { name: "Pearl", code: 84, type: 5, grade: 1 },
]

module.exports = materialCodes;